babel/minify

README.md
Small tweaks to the readme: `ECMAScript` is a trademark and thus always needs to be capitalised that way when used. Babel is a proper noun and should be capitalised too.
=> Capitalise ECMAScript and Babel

package.json, scripts/benchmark.js, scripts/fixtures/react.js
Also update benchmark script to turn off most Closure checks and use
minimal externs. A JSDoc in react.js needs to be removed because it
currently causes an unsuppressible error in Closure.
=> Update Closure Compiler to 20160822.0.0

packages/babel-preset-babili/src/index.js
+ (Close #70)
+ related #114
+ (Close #106)
=> Throw upgrade error when babel version is less than 6.14.0

packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js, packages/babel-plugin-minify-mangle-names/src/index.js, packages/babel-preset-babili/__tests__/preset-tests.js
=> Add fix for other types of nodes in referencePaths

packages/babili/src/index.js
Ref https://github.com/babel/babel.github.io/pull/898#discussion_r76549902 @loganfsmyth
=> add `--no-babelrc` option

packages/babel-preset-babili/package.json
`babel-plugin-transform-` were previous packages that already were at 6.8.0
After this is merged I'm going to run lerna again in independent mode which will republish everything and I will update these to 6.8.1
=> update older packages

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
as it probably breaks arrowFunctions
+ (close #130)
=> Don't convert expression to expression in DCE

packages/babel-plugin-minify-mangle-names/src/index.js
This gives a ~=200ms of mangler perf. 
1. If NOT shouldConsiderSource, don't traverse Identifier & Literals for charset considerations
2. Don't recalculate hasBinding
3. loops
Most time was spent getting and verifying scope's bindings. 
The following difference is between `scope.hasBinding(next)` and `bindings.hop(next)`
```
run-mangle                 740.549  1        740.549       
scopable-loop              547.912  2222     0.247         
run-collect                370.834  1        370.834       
next-identifier            222.018  3693     0.060         
get-all-bindings           171.469  2222     0.077         
Collect-Identifier         65.521   19176    0.003         
compute-oldname            54.560   64879    0.001         
scopable-rename            49.586   3693     0.013 …
```
=> Mangler performance - some improvement

packages/babel-plugin-minify-simplify/src/index.js, scripts/plugin-timing.js
Future proofing against https://github.com/babel/eslint-config-babel/pull/1.
Only two violations, even without enforcement!
=> Satisfy the "space-infix-ops" eslint rule

packages/babel-plugin-minify-replace/README.md
I couldn't get the example from README.md working, so I checked the code and realized that the replacements needed to be specified on the "replacements" key of the options object.
=> Use accurate .babelrc example for minify-replace

packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js, packages/babel-plugin-minify-mangle-names/src/index.js
~~EDIT: **DO NOT MERGE..** yet~~
~~Still doesn't cover some cases. #138~~
EDIT 1: Updated.
=> Mangle - Fix for classes and program scope

packages/babel-plugin-transform-merge-sibling-variables/__tests__/transform-merge-sibling-variables-test.js, packages/babel-plugin-transform-merge-sibling-variables/src/index.js
Only move `var` declarations into `for` loop initialisers, so `let` and `const`
declarations are still available outside the loop.
=> don't merge block-scoped sibling vars across scopes, fix #153

CHANGELOG.md, lerna.json
Generated from https://github.com/lerna/lerna-changelog
Probably want to modify it though, since it doesn't make sense with independent packages
=> add changelog [skip ci]

packages/babel-plugin-minify-guarded-expressions/__tests__/guarded-expressions-test.js, packages/babel-plugin-minify-guarded-expressions/src/index.js
An attempt at dealing with #159.
Impure statements like function calls were removed from the right-hand side of `&&` expressions if they were inferred to return a falsy value (e.g. when using the `void` operator).
This patch checks if the thing to be removed is pure. There's a lot more manual checking involved but it also simplifies more stuff.
=> don't remove impure reachable parts of logical expressions

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
+ Bail out for replacement of single use variable inside a function
TODO (for later): maybe a more intelligent approach to replace - for ex,
```js
// from
const [a] = b; return a;
const {a} = b; return a;
// to
return b[0];
return b.a;
```
+ (Close #151)
=> Fix DCE for ArrayPatterns and ObjectPatterns

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
+ (Close #167)
One other option to handle this will be to hoist var declarations as one of the first plugins. But @amasad had concerns with the hoisting effect on gzip in #52 . So this approach is okay IMO. 
`a = 1; return a; var a;` could not be reduced to `return 1` because we don't have the flow of control in the program - this is here in babel - https://github.com/babel/babel/issues/4420
=> [DCE] Fix var hoisting

packages/babel-plugin-minify-guarded-expressions/__tests__/guarded-expressions-test.js, packages/babel-plugin-minify-guarded-expressions/src/index.js
+ (close #171)
+ (close #174)
+ (close #176)
=> Fix guarded expressions

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
+ (close #163)
+ Introduces a new option for DCE - `keepFnArgs`
+ Renames - `keepFnames` to `keepFnName` for DCE
=> Remove unused fn params

packages/babel-plugin-transform-regexp-constructors/.npmignore, packages/babel-plugin-transform-regexp-constructors/README.md, packages/babel-plugin-transform-regexp-constructors/__tests__/transform-regexp-constructors-test.js, packages/babel-plugin-transform-regexp-constructors/src/index.js
Changes RegExp constructors to literals.
=> Implemented transform-regexp-constructors plugin

packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js, packages/babel-plugin-minify-mangle-names/src/index.js
=> Fix bug - mangling of name "arguments"

packages/babel-plugin-transform-regexp-constructors/README.md, packages/babel-plugin-transform-regexp-constructors/package.json, packages/babel-preset-babili/package.json
Follow-up to https://github.com/babel/babili/pull/196.
=> Integrated babel-plugin-transform-regexp-constructors into preset.

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
=> support for for..of/for..await in DCE

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js
...which involve a couple more complex conditions than `true` or `false`
=> Add more tests for DCE'ing conditional expressions

packages/babel-plugin-minify-simplify/__tests__/simplify-test.js, packages/babel-plugin-minify-simplify/src/index.js
+ (close #213)
The var declaration removal should be done in DCE instead of simplify. This is necessary as simplify as a standalone plugin should not produce syntax errors.
=> Require blocks around single block-scope declaration

packages/babel-plugin-minify-dead-code-elimination/src/index.js
This should work on babel version <6.18.0 and >6.18.0 ...
=> Fix DCE tests with labels in separate namespace

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
=> Fix array and object patterns in DCE (close #232)

packages/babel-helper-evaluate-path/.npmignore, packages/babel-helper-evaluate-path/README.md, packages/babel-helper-evaluate-path/package.json, packages/babel-helper-evaluate-path/src/index.js, packages/babel-plugin-minify-constant-folding/__tests__/constant-folding-test.js, packages/babel-plugin-minify-constant-folding/package.json, packages/babel-plugin-minify-constant-folding/src/index.js
=> Fix path.evaluate for runtime errors in constant-folding

packages/babel-plugin-minify-dead-code-elimination/src/index.js
I ran into this with one of our files. Don't have an easily reproducible testcase but maybe someone can think of something?
=> Ensure binding exists

packages/babel-plugin-transform-regexp-constructors/__tests__/transform-regexp-constructors-test.js, packages/babel-plugin-transform-regexp-constructors/src/index.js
See https://github.com/babel/babili/issues/263.
There's a comment I made in the code about the need to prettify `let a = /	/;` into `let a = /\t\;`, which have the same behavior. This makes the generated literal more clear, at the cost of 1-3 extra characters per invisible newline character when minified. I'm not convinced this beautification is necessary since it's generated code anyway.
Thoughts?
=> RegExp literal fixes

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js, packages/babel-plugin-minify-simplify/__tests__/simplify-test.js, packages/babel-plugin-minify-simplify/src/index.js
+ (Close #265)
+ (Close #257)
+ (Close #275)
=> Fix if_return & dce ifelse..return within loops

.babelrc, package.json, packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js
This should be ok since we require node >=4? (map/set, etc)
=> compile to node 4

packages/babel-preset-babili/__tests__/__snapshots__/options-tests.js.snap, packages/babel-preset-babili/__tests__/options-tests.js, packages/babel-preset-babili/package.json, packages/babel-preset-babili/src/index.js, packages/babel-preset-babili/src/options-manager.js
- (Close #54)
Each option corresponds to and enables/disables a plugin if the value is truthy. If the value is an object, it passes the object as the plugin options. The test snapshot file explains about the possibilities.
<details>
<summary>Options Manager spec:</summary>
```js
/**
* Options Manager
*
* Input Options: Object
* Output: Array of plugins enabled with their options
*
* Handles multiple types of input option keys
*
* 1. boolean and object values
* { mangle: true } // should enable mangler
* { mangle: { blacklist: ["foo"] } } // should enabled mangler
*                                    // and pass obj to mangle plugin
*
* 2. group
* { unsafe: true } // should enable all plugins under unsafe
* { unsafe: { flip: false } } // should disable flip-comparisons plugin
* …
```
=> Minify Options

packages/babel-plugin-minify-dead-code-elimination/src/index.js, packages/babel-preset-babili/__tests__/preset-tests.js
+ also fixed the test case of mangler
=> run DCE on program exit (fix #289)

packages/babel-plugin-transform-regexp-constructors/__tests__/transform-regexp-constructors-test.js, packages/babel-plugin-transform-regexp-constructors/src/index.js
[In javascript \u2028 and \u2029 count as newlines too](http://www.ecma-international.org/ecma-262/5.1/#sec-7.3) (in addition to \u000a or \n and \u000d or \r).
Since only \r and \n are properly escaped this PR adds \u2028 and \u2029.
=> Escape unicode newline in regex optimization

packages/babel-preset-babili/__tests__/options-tests.js, packages/babel-preset-babili/src/index.js
This should fix most of the bugs that are caused by using it with es2015 preset or other plugins.
=> Pass per preset the babili plugins

packages/babili/src/index.js
=> resolve babili-preset relative to babili-cli

packages/babel-plugin-minify-dead-code-elimination/README.md, packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js, packages/babel-plugin-minify-mangle-names/README.md, packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js, packages/babel-plugin-minify-mangle-names/src/index.js, packages/babel-preset-babili/__tests__/__snapshots__/options-tests.js.snap, packages/babel-preset-babili/__tests__/options-tests.js, packages/babel-preset-babili/src/index.js
Separated the `keepFnName` and updated the tests.
=> add keepClassName as separate options (fix #298)

packages/babel-plugin-minify-simplify/README.md
Adds line break in between examples (https://github.com/babel/babel.github.io/pull/1029) and fixes numbering.
=> Tweak simpify README

packages/babel-preset-babili/__tests__/preset-tests.js, packages/babel-preset-babili/src/index.js
Then we don't have to modify the readme unless we want to say somewhere it also removes comments.
This can be a bug fix (it was supposed to remove comments) or breaking change (it wasn't removing it before)
=> remove comments by default in babel-preset-babili

packages/babel-plugin-minify-mangle-names/README.md
Fixes babel/babel.github.io#1002 and following #328
=> Split code block minify-mangle-names

packages/babel-plugin-minify-dead-code-elimination/README.md
minify-dce doesn't transform `foo(0 && bar());` to `foo(0);` -- that minification is handled by minify-guarded-expressions.
=> Improve examples in README.md

packages/babel-plugin-minify-dead-code-elimination/src/index.js
Ran into this in one of our files when NOT using es2015 transform. I'll try to make a test case but don't have one for now.
=> Check binding exists

packages/babel-plugin-minify-constant-folding/__tests__/constant-folding-test.js, packages/babel-plugin-minify-constant-folding/src/index.js
=> Escape "</script" when inlining strings

packages/babel-plugin-minify-constant-folding/package.json, packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js, packages/babel-preset-babili/__tests__/preset-tests.js
TODO:
+ [x] Test case for impure statements
+ [x] Preset test cases with other plugins ?
**This moves IfStatement from program.traverse in DCE to DCEPlugin.visitor.**
+ (Fix #385)
+ Add isPure check to IfStatement visitor in DCE
+ Move IfStatement visitor from program.traverse to DCEPlugin.visitor - so that it executes for all IfStatements as babel traverse happens and NOT during the single pass within programPath.traverse in DCE. This eliminates the need for a second pass for things like the one mentioned in #385.
=> DCE: Deopt impure statements in If.test

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
=> Inline hoisted, post-return declarations properly

packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js, packages/babel-plugin-minify-mangle-names/src/index.js
=> Mark renamed paths in mangler

README.md
Further to #400. This can be changed if a command-line option for setting plugin options is added at some point.
=> Readme: plugin options cannot be set in babili cmd

packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js, packages/babel-plugin-minify-mangle-names/src/index.js
=> Fix mangler binding rename issue with duplicate names

packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js, packages/babel-plugin-minify-mangle-names/src/index.js
+ (Fixes #365)
+ (Fixes #424)
This is happening because ClassDeclarations have bindings in two scopes where as FunctionDeclarations have bindings only in the scope where it is defined.
+ https://github.com/babel/babel/issues/5156
Edit: It's not a babel bug.
Edit 2: Also changes the way topLevel is handled - removes hasOwnBinding & binding.renamed hacks
=> Handle ClassDeclaration binding

lerna.json, package.json, packages/babel-plugin-transform-remove-console/__tests__/remove-console-test.js, packages/babel-plugin-transform-remove-console/package.json, packages/babel-plugin-transform-remove-console/src/index.js, packages/babel-plugin-transform-remove-debugger/package.json
=> Fix remove console.* statements

CONTRIBUTING.md
EDIT by @hzoo: Ref https://twitter.com/mikeal/status/833810594272731137
=> Add Debugging guidelines [skip ci]

packages/babili/package.json
this info is exposed on yarnpkg.com, npmjs.com and others. If it's not filled in, the first part of the readme is used (which causes duplication).
This is the case in other packages here too. I'll make PRs for that if this one is merged.
=> chore(package): add description to babili package

packages/babel-plugin-minify-simplify/__tests__/simplify-test.js, packages/babel-plugin-minify-simplify/src/index.js
- fix #399
Adds a temporary fix for #420 - `binding not found when the path is a variableDeclaration`.
=> if_return - deopt when ref loses scope

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
(fix #419)
TODO:
+ [x] continue statements
=> Deopt do..while stmts with break

packages/babel-plugin-minify-mangle-names/src/index.js
Currently  if `array` passed as `blacklist` value  in options, `isBlacklist` method always going through the list of props.
My version instead iterate over array once and create map structure with const value accessing time.
=> Minor optimization for handling blacklisted names

packages/babel-preset-babili/src/index.js, packages/gulp-babili/.npmignore, packages/gulp-babili/README.md, packages/gulp-babili/__tests__/__snapshots__/gulp-babili-test.js.snap, packages/gulp-babili/__tests__/gulp-babili-test.js, packages/gulp-babili/package.json, packages/gulp-babili/src/index.js
TODO:
+ [ ] comments option doesn't work (@hzoo I don't know why shouldPrintComment is not called at all).
+ [x] README
=> Gulp babili

packages/gulp-babili/__tests__/__snapshots__/gulp-babili-test.js.snap, packages/gulp-babili/__tests__/gulp-babili-test.js
+ options was not passed properly.. 
+ But still couldn't figure out why the comments are removed for the previous case though..
=> Gulp Babili issue

CONTRIBUTING.md
Use absolute paths in `CONTRIBUTING.md` such that links will work on GitHub and the official website.
=> Use absolute paths in CONTRIBUTING.md

package.json, scripts/.gitignore, scripts/benchmark.js
+ (fix #465)
Outputs: 
```
Benchmark Results for react.js:
Input Size: 124.7kB
Input Size (gzip): 29.82kB
minifier          | output raw | raw win | gzip output | gzip win | parse time (ms) | minify time (ms)
babili            | 36.13kB    | 71%     | 12.6kB      | 58%      | 2.41            | 1862.94
uglify            | 35.73kB    | 71%     | 11.96kB     | 60%      | 2.32            | 820.07
closureCompiler   | 34.77kB    | 72%     | 11.96kB     | 60%      | 2.99            | 3388.90
closureCompilerJs | 65.41kB    | 48%     | 15.83kB     | 47%      | 3.00            | 1067.18
Benchmark Results for vue.js:
Input Size: 234.23kB
Input Size (gzip): 64.53kB
minifier          | output raw | raw win | gzip output | gzip win | parse time (ms) | minify time (ms)
babili            | 96.41kB    | …
```
=> Fix Benchmark scripts

packages/babel-plugin-minify-builtins/__tests__/__snapshots__/minify-builtins.js.snap, packages/babel-plugin-minify-builtins/__tests__/minify-builtins.js, packages/babel-plugin-minify-builtins/src/index.js, packages/babel-plugin-minify-mangle-names/src/index.js, packages/babel-preset-babili/__tests__/preset-tests.js
fix #461 
+ The implementation decides where to insert the created identifier based on the input code. 
Even after fixing this, the mangler doesn't rename the identifier properly. Related - https://github.com/babel/babili/issues/425
=> fix builtins plugins from leaking vars

packages/babel-plugin-minify-simplify/__tests__/simplify-test.js, packages/babel-plugin-minify-simplify/src/index.js
=> handle default statements with fallthrough properly [fix #423]

scripts/benchmark.js
Create benchmark_cache directory if it doesn't exist before downloading the default packages.
=> Create benchmark_cache dir if it doesn't exist

packages/babel-plugin-minify-constant-folding/__tests__/constant-folding-test.js, packages/babel-plugin-minify-constant-folding/package.json, packages/babel-plugin-minify-constant-folding/src/index.js
+ Fix #440, fix #413
+ Related #384, #382
=> Remove jsesc

.gitmodules, .travis.yml, circle.yml, smoke/circleci.sh
+ removes immutable-js because it fails with [memory limit 4g error](https://circleci.com/gh/babel/babili/9#tests/containers/1).
=> Add Circle CI

CONTRIBUTING.md
Updated links to use absolute paths to pass LinkCheck for babel/babel.github.io#1192.
=> Use absolute links in CONTRIBUTING.md

codecov.yml
Related: https://github.com/babel/babel/pull/5619
We face the same issues where a small coverage drop marks the PR red.
=> Set static coverage % & disable patch

packages/babel-preset-babili/README.md
One plugin was missing from the list of options in the `babel-preset-babili` README.md. (Of course it was the one plugin that was messing up my code :p).
Added doc for `minify-builtins`.
=> Add minify-builtins doc to babel-preset-babili README.md

packages/babel-plugin-minify-simplify/__tests__/simplify-test.js, packages/babel-plugin-minify-simplify/src/index.js
=> Fix crashing in simplify plugin. Deopt instead

packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js, packages/babel-plugin-minify-mangle-names/src/index.js
+ Ref #479
This completes one part of the problem where now Named exports are no
more mangled. But the other part, where we can convert
```js
const foo = bar;
export {foo};
```
to
```js
export const foo = bar;
```
is yet to be explored in DCE or other plugins.
=> Fix mangling of Named Exports in Modules

packages/babel-plugin-transform-inline-consecutive-adds/__tests__/transform-inline-consecutive-adds-test.js, packages/babel-plugin-transform-inline-consecutive-adds/src/index.js, packages/babel-plugin-transform-inline-consecutive-adds/src/set-collapser.js
This PR fix the bug for:
```js
var foo = {};
foo.bar = foo;
var foo2 = [];
foo2[2] = foo2;
var foo3 = new Set([])
foo3.add(foo3)
```
Will convert to:
```js
var foo = {bar:foo};
var foo2 = [,,foo2];
var foo3 = new Set([foo3])
```
It will get `undefined` for `var`, a ReferenceError for `let` and `const`.
I catched the problem with [`prop-types`](https://github.com/reactjs/prop-types/blob/master/factoryWithThrowingShims.js#L51) module.
=> Fix collapse with circular reference

packages/babel-plugin-minify-builtins/__tests__/__snapshots__/minify-builtins.js.snap, packages/babel-plugin-minify-builtins/__tests__/minify-builtins.js, packages/babel-plugin-minify-builtins/src/index.js
+ Deopt case was not there for classBody
+ handle the case when creating segments when the parentPath is not a function. 
+ fix #458 
+ fix #529
=> handle deopt case in builtins properly

packages/babel-plugin-minify-mangle-names/src/index.js, packages/babel-plugin-minify-mangle-names/src/scope-tracker.js
=> Polish mangle error messages

packages/babel-plugin-minify-mangle-names/src/index.js
=> Remove throwing error on unrecognized binding

smoke/smoke-test.js
Fixes https://github.com/babel/babili/issues/538.
Approach taken: perform a cleanup before a every run.  Alternative: cleanup at failure. 
I chose the former because:
* It's more robust. There could be interruption other than failure.
* Upon failure, (I guess) the minified file might be useful for troubleshooting.
=> Clean up before every run to avoid working on already minified file

packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js, packages/babel-plugin-minify-mangle-names/src/scope-tracker.js
Safari raises a syntax error for a `let` or `const` declaration in a `for` loop initalization that shadows a parent function's parameter:
```js
function a(b) {
for (let b;;);
}
```
This is valid code, but Safari throws a syntax error. The bug has been [reported](https://bugs.webkit.org/show_bug.cgi?id=171041) and since [fixed](https://trac.webkit.org/changeset/217200/webkit/trunk/Source) in WebKit, so future versions of Safari will not have this problem.
This modifies the scope tracker's `canUseInReferencedScopes` method to detect cases where a rename would trigger this bug and use a different name.
Fixes #559 
This is my first time dealing with Babel internals, so please let me know if there's a better way to do this!
=> Add workaround for Safari for loop lexical scope bug

packages/babel-plugin-minify-constant-folding/README.md, packages/babel-plugin-minify-constant-folding/__tests__/constant-folding-test.js, packages/babel-plugin-minify-constant-folding/src/index.js, packages/babel-plugin-minify-constant-folding/src/replacements.js
=> Evaluate some String and Array instance methods at compile time

packages/babel-plugin-transform-property-literals/__tests__/transform-property-literals-test.js, packages/babel-plugin-transform-property-literals/package.json, packages/babel-plugin-transform-property-literals/src/escape-string-literal.js, packages/babel-plugin-transform-property-literals/src/index.js, packages/babel-plugin-transform-property-literals/src/property-name.js
+ Fix #416 
+ Fix #445 
+ Fix #415
=> Fix removal of quotes from property names

packages/babel-plugin-minify-dead-code-elimination/src/remove-use-strict.js
- add block checks to getUseStrictDirectives()
=> fix(minify-dead-code): fix #601

packages/babel-plugin-minify-builtins/__tests__/minify-builtins.js, packages/babel-plugin-minify-constant-folding/__tests__/constant-folding-test.js, packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-flip-comparisons/__tests__/flip-comparisons-test.js, packages/babel-plugin-minify-guarded-expressions/__tests__/guarded-expressions-test.js, packages/babel-plugin-minify-infinity/__tests__/infinity-test.js, packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js, packages/babel-plugin-minify-numeric-literals/__tests__/numeric-literals-test.js, packages/babel-plugin-minify-replace/__tests__/replace-test.js, packages/babel-plugin-minify-simplify/__tests__/simplify-test.js, packages/babel-plugin-minify-type-constructors/__tests__/type-constructors-test.js, packages/babel-plugin-transform-inline-consecutive-adds/__tests__/transform-inline-consecutive-adds-test.js, packages/babel-plugin-transform-inline-environment-variables/__tests__/inline-env-var-test.js, packages/babel-plugin-transform-member-expression-literals/__tests__/transform-member-expression-literals-test.js, packages/babel-plugin-transform-merge-sibling-variables/__tests__/transform-merge-sibling-variables-test.js, packages/babel-plugin-transform-minify-booleans/__tests__/booleans-test.js, packages/babel-plugin-transform-node-env-inline/__tests__/node-env-inline-test.js, packages/babel-plugin-transform-property-literals/__tests__/transform-property-literals-test.js, packages/babel-plugin-transform-regexp-constructors/__tests__/transform-regexp-constructors-test.js, packages/babel-plugin-transform-remove-console/__tests__/remove-console-test.js, packages/babel-plugin-transform-remove-debugger/__tests__/remove-debugger-test.js, packages/babel-plugin-transform-remove-undefined/__tests__/babel-plugin-transform-remove-undefined-test.js, packages/babel-plugin-transform-simplify-comparison-operators/__tests__/strict-equals-test.js, packages/babel-plugin-transform-undefined-to-void/__tests__/undefined-test.js, packages/babel-preset-babili/__tests__/preset-tests.js, utils/test-transform.js
This adds a test helper that creates a testing function, which is usually called `thePlugin`, which streamlines testing transforms. I’ve also gone through and edited some of the test names for clarity.
=> Refactor the test suite

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
=> [DCE] Fix removal of ArrayPattern

packages/babel-plugin-minify-simplify/__tests__/simplify-test.js, packages/babel-plugin-minify-simplify/src/index.js
Eliminate unnecessary `return` keyword by converting arrow function block statements to expressions where possible.
Example:
```js
const foo = () => {
return (1, 2);
};
const bar = () => {
return [];
};
// becomes
const foo = () => (1, 2);
const bar = () => [];
```
=> Convert simple arrow function body to expression

packages/babel-plugin-minify-simplify/__tests__/simplify-test.js, packages/babel-plugin-minify-simplify/src/index.js
=> Fix block removal during early continue transform

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
=> Detect duplicate declaration during one-use replacement

package.json, packages/babel-plugin-transform-remove-undefined/src/index.js, packages/babel-preset-babili/__tests__/babili-es2015-tests.js, packages/babel-preset-babili/package.json, yarn.lock
@boopathi Shall we keep a separate preset test along with es2015 just for these kind of issues.
=> binding voilations check during es2015 transform[fix #630]

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
+ Fix #574 
this is required for only var bindings. 
The other way we could fix this is to hoist all the var bindings before we run simplify & deadcode.
=> [fix #574] deopt when binding is present in diff scope

packages/babel-helper-evaluate-path/src/index.js
Adding tests for evaluate-helper later. Currently it's handled in other plugins - simplify, due, etc...
=> Add deopt paths for let/const bindings in evaluate helper

packages/babel-helper-evaluate-path/src/index.js, packages/babel-minify/src/cli.js, packages/babel-plugin-minify-builtins/README.md, packages/babel-plugin-minify-builtins/src/index.js, packages/babel-plugin-minify-constant-folding/README.md, packages/babel-plugin-minify-constant-folding/src/index.js, packages/babel-plugin-minify-dead-code-elimination/README.md, packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js, packages/babel-preset-minify/README.md, packages/babel-preset-minify/src/index.js
For common case, detecting tdz isn't required. Make it optional.
=> Make tdz optional in helper evaluate

packages/babel-plugin-transform-remove-undefined/README.md, packages/babel-plugin-transform-remove-undefined/package.json, packages/babel-plugin-transform-remove-undefined/src/index.js, packages/babel-preset-minify/README.md, packages/babel-preset-minify/__tests__/babili-es2015-tests.js, packages/babel-preset-minify/src/index.js
+ [x] Add option `tdz` in transform-remove-undefined
+ [x] Udpate tdz option in preset
+ [x] Update docs
+ [x] Tests
Fix #614
=> Use evaluate helper in removeUndefined transform

packages/babel-plugin-minify-constant-folding/__tests__/constant-folding-test.js, packages/babel-plugin-minify-constant-folding/src/index.js, packages/babel-plugin-minify-constant-folding/src/replacements.js
The `.join()` inlining function was checking for `isLiteral()` on each array element, and then using the element's `.value`. Some literals don't have `.value`s though: null literals, regexp literals and template literals.
This patch fixes `.join()`ing regexp literals and bails out of joining template literals entirely. 
Null literals already did the right thing despite not having a `.value`, because `.join()` appears to treat `undefined` and `null` the same.
=> constant-folding: Fix some literal types used in `.join()`, closes #612

packages/babel-plugin-transform-remove-console/README.md, packages/babel-plugin-transform-remove-console/__tests__/remove-console-test.js, packages/babel-plugin-transform-remove-console/src/index.js
An attempt to implement the extension requested in https://github.com/babel/minify/issues/598
Based on the unit tests I added, I believe this is working, however as this is my very first attempt at code within the babel ecosystem it is highly likely there are better ways to approach this. I welcome any and all feedback on how to improve this either functionally or idiomatically.
=> Add exclude option for transform-remove-console plugin

packages/babel-plugin-minify-numeric-literals/__tests__/numeric-literals-test.js, packages/babel-plugin-minify-numeric-literals/src/index.js
I went ahead and rewrote the test suite for minify-numeric-literals, and came across a number of issues:
- `0xa` should transform to `10`, instead of `0xa`
- `0x64` should transform to `100` instead of `1e2` (opinionated, better gzip?)
- `0o12` should transform to `10` instead of `1e1`
- `0o144` should transform to `100` instead of `1e2` (opinionated, better gzip?)
- `0b1010` should transform to `10` instead of `1e1`
- `0b1100100` should transform to `100` instead of `1e2` (opinionated, better gzip?)
- `0.123456` should transform to `.123456` instead of `0.123456`
- `1.5e3` should transform to `1500` instead of `1.5e3`
- `1e-1` should transform to `.1`  instead of `1e-1`
- `1e-2` should transform to `.01`  instead of `1e-2`
- `1e-3` should transform to `.001`  instead of `1e-3` …
=> Refactor minify-numeric-literals.

packages/babel-minify/src/cli.js, packages/babel-minify/src/fs.js
=> Fix js ext check & improve error handling for file list

packages/babel-plugin-minify-constant-folding/__tests__/constant-folding-test.js, packages/babel-plugin-minify-constant-folding/src/index.js, packages/babel-plugin-minify-constant-folding/src/replacements.js
+ Fixes #695
+ Fixes #628
+ Related #610
=> Fix folding array literals - bail on spread element

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
=> fix(dce): extract only binding identifiers during block removal

.gitattributes
scripts/gcc.jar always showed up as being modified, because git was
replacing the newlines in this binary file.
=> Specify *.jar as binary in gitattributes

packages/babel-plugin-transform-merge-sibling-variables/src/index.js, packages/babel-preset-minify/__tests__/babili-es2015-tests.js
Fix #594
Fix #430
Fix #412 
Fix #554
Fix #581
Fix #477 
Fix #720
=> Fix(merge-sibling-var): force recalc ref when concat for-loop var (#485)

packages/babel-plugin-minify-constant-folding/src/index.js, packages/babel-preset-minify/__tests__/preset-tests.js
+ t.valueToNode(<objectExpressionNode>) returns an object expression
node and again but with a few other effects - it removes the quotes from
property names for some unicode which is not supported in Safari and a
few other older browsers. So we bail here and let propertyLiterals
plugin handle the conversion of StringLiterals to Identifiers.
+ Fix #627
+ Fix #706
=> fix: property names minification - removal of quotes

packages/babel-plugin-transform-regexp-constructors/__tests__/transform-regexp-constructors-test.js, packages/babel-plugin-transform-regexp-constructors/src/index.js
=> Bugfix Regex's containing (\0)

packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/toplevel-class/actual.js, packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/toplevel-class/expected.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
Apply the same trick we use in mangler to detect toplevel classes
+ Fix #741
=> fix(dce): don't remove toplevel classes

packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/issue-685/actual.js, packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/issue-685/expected.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js
In one use variable replacement, if the right hand side contains
constant violations, the left-hand side is supposed to be preserved, so
we detect this and bail out for this case
+ Fix #685
=> fix(dce): bail on non-constant replacement path

packages/babel-plugin-minify-mangle-names/src/fixup-var-scoping.js
handle getFunctionParen not returning a Program
Due to [this](https://github.com/babel/babel/pull/5923) change, mangle-names does not work with Babel 7 without this update.
=> babel 7 compatibility change - mangle names: 

packages/babel-plugin-minify-mangle-names/__tests__/fixtures/issue-366/actual.js, packages/babel-plugin-minify-mangle-names/__tests__/fixtures/issue-366/expected.js, packages/babel-plugin-minify-mangle-names/src/index.js
We were always checking the wrong scope that was marked by DCE in another pass. 
+ fixes #366 
+ fixes #605
=> fix(mangle) - mark the correct eval scope during mangling

packages/babel-plugin-minify-builtins/__tests__/fixtures/props-polyfilled/actual.js, packages/babel-plugin-minify-builtins/__tests__/fixtures/props-polyfilled/expected.js, packages/babel-plugin-minify-builtins/src/index.js
+ Bailing on computed member expressions when its polyfilled
+ fixes #738
=> fix builtins - bail on polyfilled members

packages/babel-plugin-minify-simplify/src/conditional-expression.js, packages/babel-preset-minify/__tests__/preset-tests.js
Expression and LogicalExpression handled separately causes the issues as
mentioned in the issue below. So we handle only Expressions and ignore
LogicalExpressions.
+ fix #769
=> fix(simplify): remove redundant patterns

packages/babel-plugin-transform-inline-consecutive-adds/src/index.js
This yields us a huge **3.5x improvement** on a test file > 2MB. 
```
pluginAlias                       time(ms)
// Before
transform-inline-consecutive-adds - 5716.129
transform-inline-consecutive-adds - 5752.153
transform-inline-consecutive-adds - 5813.064
// After
transform-inline-consecutive-adds - 1624.955
transform-inline-consecutive-adds - 1925.298
transform-inline-consecutive-adds - 1788.473
```
Thanks to chrome devtools for helping to find the root cause. Confirmation from devtools
=> (perf) - move the collapser check before inling properties

.eslintrc.js
This [marks the file as the root config](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) to prevent ESLint from looking for config files in parent directories.
=> chore(eslint): mark as root config

packages/babel-plugin-minify-constant-folding/src/index.js
We found that `traverse.hasType` introduces a lot of side-effects since its create cache entries for path where scope might not be defined.
If this method is called for a path that has never been created, it will bound the wrong scope object to it, causing subsequent access to throw.
For example this exception:
```
TypeError: Cannot read property 'getBinding' of null
```
can be traced down to this exact problem.
FYI this is the exact same failure we have on the CI.
=> fix: Remove unnecessary checks for constant folding

packages/babel-plugin-transform-merge-sibling-variables/src/index.js, packages/babel-preset-minify/__tests__/minify-env-tests.js
=> fix(merge-sibling-var): recalculate declarations when concatenating variables

packages/babel-preset-minify/src/index.js
Within babel-preset-minify, if you pass an options object for one of the plugins that is disabled by default (like removeConsole) it does not get enabled.
This PR fixes that, just ensuring any plugin you are setting options for is also enabled.
=> Allow options for plugins disabled by default (babel-preset-minify)

packages/babel-plugin-minify-constant-folding/__tests__/fixtures/export-specifier/actual.js, packages/babel-plugin-minify-constant-folding/__tests__/fixtures/export-specifier/babel.json, packages/babel-plugin-minify-constant-folding/__tests__/fixtures/export-specifier/expected.js, packages/babel-plugin-minify-constant-folding/src/index.js
=> fix(const-folding): do not evaluate identifier in export specifiers

packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/loops/actual.js, packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/loops/expected.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js, packages/babel-preset-minify/__tests__/minify-env-tests.js
=> fix(deadcode): account for impure paths inside for statements

packages/babel-helper-evaluate-path/src/index.js, packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/issue-574/expected.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js, packages/babel-plugin-minify-guarded-expressions/src/index.js, packages/babel-plugin-minify-simplify/src/helpers.js, packages/babel-plugin-minify-simplify/src/logical-expression.js, packages/babel-preset-minify/__tests__/preset-tests.js
+ fix #810 
+ fix #574  properly
=> fix: account for different scopes during path evaluation

packages/babel-plugin-minify-infinity/__tests__/fixtures/bindings/actual.js, packages/babel-plugin-minify-infinity/__tests__/fixtures/bindings/expected.js, packages/babel-plugin-minify-infinity/__tests__/fixtures/expressions/actual.js, packages/babel-plugin-minify-infinity/__tests__/fixtures/expressions/expected.js, packages/babel-plugin-minify-infinity/src/index.js
=> fix: minify infinity in expressions

packages/babel-plugin-minify-mangle-names/src/index.js, packages/babel-preset-minify/__tests__/minify-env-tests.js
The t.NOT_LOCAL_BINDING symbol used in plugin-function-name
(https://github.com/babel/babel/blob/bd98041321c60737ddcacd1ad7e056ef6de31879/packages/babel-helper-function-name/src/index.js#L206)
is causing this issue.
This was added in babel/babel#3298
The problem is the binding identifier is NOT registered (skipped) during
crawl and the mangler finds the first safe identifier which ultimately
collides with this name during runtime.
So, we register the binding and don't respect the t.NOT_LOCAL_BINDING.
Fix #829
=> fix(mangle): handle inferred names for functions

packages/babel-plugin-minify-mangle-names/src/index.js
This is to better measure the performance of individual items. `mangleScope` is one of the slowest APIs in babel-minify.
=> refactor: split mangleScope logic to smaller functions

packages/babel-helper-evaluate-path/src/index.js
Has a significant improvement on lodash (measured using `scripts/plugin-timing.js`) as tested on node 9.
from `~= 3300ms` to `~=1900ms`
=> perf(evaluate): convert paths to nodes as path.get is slow

packages/babel-plugin-minify-builtins/src/index.js
+ this is a micro optimisation for built-ins transform
+ Yields around ~30-40 ms on `three.js`
=> perf(builtins): remove path.get calls

packages/babel-plugin-minify-builtins/__tests__/fixtures/builtin-methods/expected.js, packages/babel-plugin-minify-builtins/__tests__/fixtures/evaluate-builtins/expected.js, packages/babel-plugin-minify-builtins/__tests__/fixtures/in-function-scope/expected.js, packages/babel-plugin-minify-builtins/__tests__/fixtures/local-binding/actual.js, packages/babel-plugin-minify-builtins/__tests__/fixtures/local-binding/expected.js, packages/babel-plugin-minify-builtins/package.json, packages/babel-plugin-minify-builtins/src/index.js
+ This improves the performance approximately from ~600ms to ~250ms on a 2mb file.
=> perf(builtins): run builtins transform on multi pass

packages/gulp-babel-minify/src/index.js
The following changes were applied:
- Added a condition where the property "file" is checked. If it
doesn't exist it is copied from the original source file.
P.S: I just saw that the indentation of the closing brace is wrong (Vim's fault).
=> Fix issue #862

.github/ISSUE_TEMPLATE/Bug_report.md, package.json, packages/babel-minify/package.json, packages/babel-plugin-minify-simplify/__tests__/simplify-test.js, packages/gulp-babel-minify/package.json, yarn.lock
**Changes**:
* Update babel version
* Update tests because of changes made for better `NaN` handling (https://github.com/babel/babel/pull/8005)
=> chore: Update babel to 7.0.0-beta.49

packages/babel-plugin-minify-dead-code-elimination/src/index.js, packages/babel-preset-minify/__tests__/preset-tests.js
=> fix(deadcode): sequence expressions in switch discriminant

README.md
Earlier link was giving 404 error
=> Update link to babili blog post

package.json
Upgrading to lerna 3 broke the canary publishing. I missed correcting it in PR #900. So, here's the fix.
=> Fix canary publishing

.travis.yml
Lerna canary doesn't work correctly with shallow clones.
From https://github.com/lerna/lerna/issues/1583#issuecomment-424596666.
@boopathi I can also incorporate #906 if you decide on it.
From #900 
> So, basically, once this PR is merged and you guys publish all the packages, the license issues will be fixed.
You haven't published all the packages. Only the packages which got changed, got published. Which means, the licensing issues still exist for older packages. Can you do a `lerna publish --force-publish` to fix this? (A new patch version should be good enough). Very important for us.
=> chore: Don't do shallow clones on travis

packages/babel-preset-minify/README.md
Making it obvious that the first argument to `.transform()` is a code string and that the return value is minified code.
=> Clarifying use of Node API

.gitignore, packages/babel-minify/__tests__/__snapshots__/cli-tests.js.snap, packages/babel-minify/__tests__/fixtures/module/mod.js, packages/babel-minify/package.json, packages/babel-minify/src/cli.js, packages/babel-plugin-minify-dead-code-elimination/package.json, packages/babel-plugin-minify-dead-code-elimination/src/index.js, packages/babel-preset-minify/package.json, packages/babel-preset-minify/src/index.js, yarn.lock
What:
Updated use of lodash to lodash/somefunc instead of lodash.somefunc:
* upgraded lodash deps to ^4.17.11
* updated requires from lodash.somefunc to lodash/somefunc
* updates snapshots
re-ran bootstrap, build and test
Why:
Updated to remediate CVE-2018-3721 - where modularized packages are specifically vulnerable, and as modularized packages are deprecated, no updates have been released in about 2 years.
=> chore(minify): remediate CVE-2018-3721: update lodash to latest, remove use of deprecated module packages

packages/babel-plugin-minify-guarded-expressions/package.json
This causes an error to be thrown when using Yarn with pnp enabled.
=> babel-helper-evaluate-path is not listed as a dependency but is used as one.

packages/babel-plugin-minify-simplify/package.json
Fixes https://github.com/babel/minify/issues/884
Related to https://github.com/babel/minify/pull/963
=> add missing babel-helper-evaluate-path pkg

packages/babel-plugin-transform-inline-environment-variables/__tests__/inline-env-var-test.js, packages/babel-plugin-transform-inline-environment-variables/src/index.js
The following code reproduce the bug:
```js
if(process.env.NODE_ENV !== "production"){
process.env.NODE_ENV = "development"; // an error occurred
// ...
}
```
```bash
babel --plugins transform-inline-environment-variables script.js
```
> TypeError: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "StringLiteral"
=> fix: an error occurred if includes environment variable assignment expression

package.json, packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/fn-params/expected.js, packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/fn-this/actual.js, packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/fn-this/expected.js, packages/babel-plugin-minify-dead-code-elimination/src/index.js, packages/babel-plugin-minify-mangle-names/__tests__/fixtures/constant-violations-2/expected.js, packages/babel-plugin-minify-mangle-names/__tests__/fixtures/issue-822/expected.js, packages/babel-plugin-minify-mangle-names/__tests__/fixtures/keep-class-name/expected.js, packages/babel-plugin-minify-mangle-names/__tests__/fixtures/reuse/expected.js, packages/babel-preset-minify/__tests__/minify-env-tests.js, utils/test-runner/src/index.js, yarn.lock
From now on just bail on `ThisExpression`.
For further improvement ideas, see https://github.com/babel/minify/issues/1028#issuecomment-1114982399
=> Do not inline `this`
