packages/babel-plugin-minify-simplify/__tests__/simplify-test.js
packages/babel-plugin-minify-simplify/src/index.js

Fix bug - Conditionals transformation for impure paths

---

packages/babel-preset-babili/src/index.js

Revert "Throw upgrade error when babel version is less than 6.14.0"

---

README.md

Before, the `[] Minify (Babili)` checkbox wasn't checked.  Now it is, & includes the example code below.

enhansed live example link

---

README.md

improve benchmark description

---

CHANGELOG.md

Changelog for 2016-09-30 [skip ci]

---

packages/babel-preset-babili/src/index.js

Adds babel-plugin-transform-regexp-constructors to preset.

---

packages/babel-plugin-minify-simplify/__tests__/simplify-test.js
packages/babel-plugin-minify-simplify/src/index.js

Fix for merging of vars to successive for loop

---

CHANGELOG.md

changelog [skip ci]

---

README.md

cc @iamdustan
A litte bit smaller

update benchmarks for v0.0.8 [skip ci]

---

packages/babel-plugin-minify-infinity/__tests__/infinity-test.js
packages/babel-plugin-minify-infinity/src/index.js

fix for infinity as lval

---

packages/babel-plugin-minify-simplify/__tests__/simplify-test.js
packages/babel-plugin-minify-simplify/src/index.js

Fix labeled break stmt removal from last switch case

---

packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js
packages/babel-plugin-minify-dead-code-elimination/src/index.js

Remove Empty Functions in block 

---

packages/babel-plugin-transform-regexp-constructors/__tests__/transform-regexp-constructors-test.js
packages/babel-plugin-transform-regexp-constructors/src/index.js

Fixed test broken in https://github.com/babel/babili/pull/264.

Regexp test fixes

---

packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js
packages/babel-plugin-minify-mangle-names/src/index.js
packages/babel-preset-babili/__tests__/preset-tests.js

Revert "Mangler - reuse removed vars"

---

packages/babel-plugin-minify-simplify/__tests__/simplify-test.js
packages/babel-plugin-minify-simplify/src/index.js

Don't transform earlyReturn on function enter

---

CHANGELOG.md

Feel free to add/edit/comment.

Add Changelog for 0.0.9 [skip ci]

---

packages/babel-plugin-minify-dead-code-elimination/src/index.js

Fix dce - recompute path & scope before pass

---

packages/babel-plugin-minify-replace/README.md

Fixes babel/babel.github.io#1002

Split code blocks minify-replace

---

README.md

add install, removing #redundancy [skip ci]

---

packages/babel-plugin-minify-mangle-names/src/index.js

Clear traverse cache and recrawl for mangler

---

packages/babel-plugin-transform-merge-sibling-variables/src/index.js
packages/babel-preset-babili/__tests__/preset-tests.js

The mutation was causing the DCE to error out.

lift the declarations without mutating the node[fix #402]

---

CONTRIBUTING.md

Added example of running tests for one of the packages

Update CONTRIBUTING.md [skip ci]

---

smoke/run.js

Lodash is not updated because of this - 
https://github.com/lodash/lodash/blob/98969648e99423e3815a70b2611b2bf1509ca768/.github/CONTRIBUTING.md#construction-notice-construction

Update smoke test assets to latest versions

---

packages/gulp-babili/package.json

Add gulp-babili dependencies.

---

packages/babel-helper-mark-eval-scopes/__tests__/helper-mark-eval-scopes-test.js
packages/babel-plugin-minify-dead-code-elimination/src/index.js
packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js
packages/babel-plugin-minify-mangle-names/src/index.js

Support babel 7

---

packages/babel-plugin-minify-simplify/__tests__/simplify-test.js
packages/babel-plugin-minify-simplify/src/if-statement.js

Don't remove else with blockscoped decl

---

packages/babel-plugin-minify-numeric-literals/README.md

Update title in readme to match plugin name

Update babel-plugin-minify-numeric-literals README

---

packages/babel-helper-evaluate-path/src/index.js

Ref: https://github.com/babel/babel/pull/5980

Fix evaluate helper

---

packages/babel-helper-to-multiple-sequence-expressions/src/index.js
packages/babel-preset-minify/__tests__/babili-es2015-tests.js

Fix helper toMultipleSeqExpr with es2015

---

packages/babel-minify/src/cli.js

CLI: reorder files/stdin/help-message

---

packages/babel-minify/src/cli.js
packages/babel-plugin-minify-mangle-names/README.md
packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js
packages/babel-plugin-minify-mangle-names/src/index.js
packages/babel-preset-minify/README.md
packages/babel-preset-minify/__tests__/__snapshots__/options-tests.js.snap
packages/babel-preset-minify/__tests__/options-tests.js
packages/gulp-babel-minify/__tests__/gulp-babili-test.js

The next version will be `0.3.0`.

[mangle] blacklist -> exclude

---

packages/babel-plugin-transform-inline-environment-variables/README.md
packages/babel-plugin-transform-inline-environment-variables/__tests__/inline-env-var-test.js
packages/babel-plugin-transform-inline-environment-variables/src/index.js

Add whitelist/blacklist to transform-inline-environment-variables

---

.travis.yml
appveyor.yml
circle.yml

+ Upgrade yarn
+ remove yarn bootstrap (unnecessary)
+ update circle ci yarn cache

Update CI yml files

---

.travis.yml
package.json

ci(build-stages): Publish nightly

---

docs/README.md

add master auto-publish docs

---

packages/babel-plugin-minify-simplify/__tests__/simplify-test.js
packages/babel-plugin-minify-simplify/src/conditional-expression.js

fix(simplify): fix conditional expression pattern match transformation logic

---

.babelrc
.travis.yml
README.md
appveyor.yml
package.json

Ref: #766 - decision was made here.
Late to the game?

Remove node 4. Add node 9

---

packages/gulp-babel-minify/package.json
packages/gulp-babel-minify/src/index.js
yarn.lock

[Context](https://github.com/gulpjs/gulp-util/issues/143)

Remove gulp-util dependency

---

packages/babel-plugin-minify-constant-folding/src/index.js

fix(evaluate): handle only string concat bin expression

---

packages/babel-plugin-minify-mangle-names/README.md

- Correct error in config with options (no double array)
- Add default options in options list

Fixes in README

---

packages/babel-plugin-minify-constant-folding/src/index.js

Just a small typo I noticed while reading the code.

Fix some comment typo

---

packages/babel-plugin-minify-mangle-names/__tests__/fixtures/issue-822/actual.js
packages/babel-plugin-minify-mangle-names/__tests__/fixtures/issue-822/expected.js
packages/babel-plugin-minify-mangle-names/src/index.js

fix #822 
~~Obviously, this doesn't seem to work and introduces more regression. The Circle CI tests fail. Working on an update.~~
Update: fixed

fix: add constant violations to references in mangler collect phase

---

packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/issue-871/actual.js
packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/issue-871/expected.js
packages/babel-plugin-minify-dead-code-elimination/src/index.js

fix(dce): handle array and object patterns in assignment expressions

---

package.json
packages/babel-minify/package.json
packages/gulp-babel-minify/package.json
yarn.lock

Just an update to the latest babel version

chore: update to babel 7.0.0-beta.54

---

README.md

Node.js@6.0+ is supported.  
https://github.com/babel/minify/blob/55b6e50a5b7916f26842498bd0a09629986e6826/package.json#L56-L59

chore: update Requirements section in README.md

---

packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/issue-922/actual.js
packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/issue-922/expected.js
packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/loops/expected.js
packages/babel-plugin-minify-dead-code-elimination/src/index.js

Fixes #922, extractVars instead of path removal
